// Package authtoken manages patrabahokd API bearer tokens. Only a SHA-256 hash of
// each token is ever stored — the plaintext is shown once, at creation time, and
// cannot be recovered afterward. This is deliberately a fast hash (not a slow KDF
// like argon2id): tokens are high-entropy random values generated by us, not
// low-entropy human-chosen secrets, so the threat model a slow KDF defends against
// (offline brute-force of a guessable secret) doesn't apply here.
package authtoken

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"
)

const tokenPrefix = "pbk_"

type TokenInfo struct {
	ID         int64
	Name       string
	Scopes     []string
	CreatedAt  time.Time
	LastUsedAt *time.Time
}

func (t *TokenInfo) HasScope(required string) bool {
	for _, s := range t.Scopes {
		if s == "*" || s == required {
			return true
		}
	}
	return false
}

var ErrInvalidToken = errors.New("invalid or revoked token")

type Store struct {
	db *sql.DB
}

func NewStore(db *sql.DB) *Store {
	return &Store{db: db}
}

func generatePlaintext() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return tokenPrefix + hex.EncodeToString(b), nil
}

func hashToken(plaintext string) string {
	sum := sha256.Sum256([]byte(plaintext))
	return hex.EncodeToString(sum[:])
}

// Create generates a new token and returns its plaintext value. The plaintext is
// never stored — the caller must show it to the user immediately and discard it.
func (s *Store) Create(ctx context.Context, name string, scopes []string) (plaintext string, err error) {
	if name == "" {
		return "", fmt.Errorf("token name is required")
	}
	if len(scopes) == 0 {
		scopes = []string{"*"}
	}
	plaintext, err = generatePlaintext()
	if err != nil {
		return "", err
	}
	_, err = s.db.ExecContext(ctx, `
		INSERT INTO api_tokens (name, token_hash, scopes) VALUES (?, ?, ?)`,
		name, hashToken(plaintext), strings.Join(scopes, ","))
	if err != nil {
		return "", err
	}
	return plaintext, nil
}

func (s *Store) List(ctx context.Context) ([]TokenInfo, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT id, name, scopes, created_at, last_used_at FROM api_tokens ORDER BY id`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []TokenInfo
	for rows.Next() {
		var t TokenInfo
		var scopes string
		var lastUsed sql.NullTime
		if err := rows.Scan(&t.ID, &t.Name, &scopes, &t.CreatedAt, &lastUsed); err != nil {
			return nil, err
		}
		t.Scopes = strings.Split(scopes, ",")
		if lastUsed.Valid {
			t.LastUsedAt = &lastUsed.Time
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

func (s *Store) Revoke(ctx context.Context, name string) error {
	res, err := s.db.ExecContext(ctx, `DELETE FROM api_tokens WHERE name = ?`, name)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("no token named %q", name)
	}
	return nil
}

// Verify looks up a presented bearer token and records its use. Returns
// ErrInvalidToken if the token doesn't match any stored hash.
func (s *Store) Verify(ctx context.Context, plaintext string) (*TokenInfo, error) {
	if plaintext == "" {
		return nil, ErrInvalidToken
	}
	hash := hashToken(plaintext)
	var t TokenInfo
	var scopes string
	err := s.db.QueryRowContext(ctx, `
		SELECT id, name, scopes FROM api_tokens WHERE token_hash = ?`, hash,
	).Scan(&t.ID, &t.Name, &scopes)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrInvalidToken
	}
	if err != nil {
		return nil, err
	}
	t.Scopes = strings.Split(scopes, ",")

	_, _ = s.db.ExecContext(ctx, `UPDATE api_tokens SET last_used_at = NOW() WHERE id = ?`, t.ID)
	return &t, nil
}
